spring:
  application:
    name: orders-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ordersdb}

    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: ${APP_KAFKA_TOPIC:orders.events}
    consumer:
      group-id: orders-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  server:
    port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    otlp:
      tracing:
        endpoint: http://jaeger:4317
        protocol: grpc
    metrics:
      export:
        simple:
          enabled: false